<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/DeepLearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.Series([1,2,3])
data

0    1
1    2
2    3
dtype: int64

In [ ]:
data[1]

np.int64(2)

In [ ]:
var={
    "cal":[100,200,300],
    "dura":[12,14,16]
}
df=pd.DataFrame(var)
df

   cal  dura
0  100    12
1  200    14
2  300    16

In [ ]:
print(df.loc[2])

cal     300
dura     16
Name: 2, dtype: int64

In [ ]:
print(type(df.loc[2]))

<class 'pandas.core.series.Series'>

In [ ]:
print(df.loc[[0,1]])

   cal  dura
0  100    12
1  200    14

In [9]:
print(df.loc[0])

cal     100
dura     12
Name: 0, dtype: int64

In [16]:
var2={
    "cal":[100,200,300],
    "val":[1,2,3]
}
data=pd.DataFrame(var2,index=["x","y","z"])

In [17]:
data

   cal  val
x  100    1
y  200    2
z  300    3

# Introduction to Pytorch

In [18]:
import torch

In [19]:
torch.__version__

'2.11.0+cpu'

In [22]:
a=torch.tensor(7.2)
print(a)
print(a.item())
print(a.dtype)

tensor(7.2000)
7.199999809265137
torch.float32

In [23]:
b=torch.tensor(12)
print(b)

tensor(12)

In [24]:
b.item()

12

In [25]:
b.dtype

torch.int64

In [26]:
print(b.shape)

torch.Size([])

In [28]:
print(b.size())

torch.Size([])

In [30]:
dimension=a.ndim
print(dimension)

0

Defining a list

In [32]:
a=torch.tensor([1.0,2.0,3.0])
print(a)
# print(a.item()) this will not be printed as there are multiple elements
print(a.dtype)
print(a.shape)
print(a.size())

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
torch.Size([3])

In [33]:
print(a.ndim)

1

In [34]:
print(a[0].item())

1.0

In [35]:
# sum of all elem
print(torch.sum(a).item())

6.0

In [36]:
print(torch.mean(a).item())

2.0

In [37]:
print(torch.norm(a).item())

3.7416574954986572