<a href="https://colab.research.google.com/github/24f3003058/DL-GenAI/blob/main/DeepLearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.Series([1,2,3])
data

0    1
1    2
2    3
dtype: int64

In [3]:
data[1]

np.int64(2)

In [4]:
var={
    "cal":[100,200,300],
    "dura":[12,14,16]
}
df=pd.DataFrame(var)
df

   cal  dura
0  100    12
1  200    14
2  300    16

In [5]:
print(df.loc[2])

cal     300
dura     16
Name: 2, dtype: int64

In [6]:
print(type(df.loc[2]))

<class 'pandas.core.series.Series'>

In [7]:
print(df.loc[[0,1]])

   cal  dura
0  100    12
1  200    14

In [8]:
print(df.loc[0])

cal     100
dura     12
Name: 0, dtype: int64

In [9]:
var2={
    "cal":[100,200,300],
    "val":[1,2,3]
}
data=pd.DataFrame(var2,index=["x","y","z"])

In [10]:
data

   cal  val
x  100    1
y  200    2
z  300    3

# Introduction to Pytorch

In [11]:
import torch

In [12]:
torch.__version__

'2.11.0+cpu'

In [13]:
a=torch.tensor(7.2)
print(a)
print(a.item())
print(a.dtype)

tensor(7.2000)
7.199999809265137
torch.float32

In [14]:
b=torch.tensor(12)
print(b)

tensor(12)

In [15]:
b.item()

12

In [16]:
b.dtype

torch.int64

In [17]:
print(b.shape)

torch.Size([])

In [18]:
print(b.size())

torch.Size([])

In [19]:
dimension=a.ndim
print(dimension)

0

Defining a list

In [20]:
a=torch.tensor([1.0,2.0,3.0])
print(a)
# print(a.item()) this will not be printed as there are multiple elements
print(a.dtype)
print(a.shape)
print(a.size())

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
torch.Size([3])

In [21]:
print(a.ndim)

1

In [22]:
print(a[0].item())

1.0

In [23]:
# sum of all elem
print(torch.sum(a).item())

6.0

In [24]:
print(torch.mean(a).item())

2.0

In [25]:
print(torch.norm(a).item())

3.7416574954986572

In [26]:
b=torch.tensor([
    [1,2,3],
    [4,5,6]
    ])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
print(b.dtype)

torch.int64

In [28]:
print(b.shape)

torch.Size([2, 3])

In [29]:
print(b.size())

torch.Size([2, 3])

In [30]:
print(b.ndim)

2

In [31]:
a=torch.tensor([[[7,8],[0,1]],[[1,5],[4,6]]])
print(a)

tensor([[[7, 8],
         [0, 1]],

        [[1, 5],
         [4, 6]]])

In [32]:
print(a.size())

torch.Size([2, 2, 2])

In [33]:
print(a.ndim)

3

In [34]:
zero=torch.zeros(3,4)
print(zero)
print(zero.shape)
print(zero.dtype)
print(zero.device)
print(zero.numel())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
torch.float32
cpu
12

In [35]:
print(zero.element_size() * zero.numel()) # memory in bytes

48

In [36]:
print(torch.sum(zero).item())

0.0

In [37]:
print(torch.std(zero).item())

0.0

In [38]:
one=torch.ones(3,4)
print(one)
print(one.shape)
print(one.dtype)
print(one.ndim)
print(one.numel())
print(one.device)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])
torch.float32
2
12
cpu

In [39]:
random =torch.rand(4,4)
print(random)

tensor([[0.2840, 0.4449, 0.6435, 0.6775],
        [0.5271, 0.0522, 0.5186, 0.6804],
        [0.7241, 0.4594, 0.5908, 0.2027],
        [0.5935, 0.6636, 0.4444, 0.5242]])

In [40]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random=torch.rand(4,4)
print(random)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])

Mathematical Operations on tensors

In [41]:
var=torch.tensor([10,20,30])
var + 10

tensor([20, 30, 40])

In [42]:
var -10

tensor([ 0, 10, 20])

In [43]:
var * 10

tensor([100, 200, 300])

In [44]:
var * var

tensor([100, 400, 900])

In [45]:
print(var)
matrix_result=torch.matmul(var,var)
print(matrix_result)
print(torch._make_per_tensor_quantized_tensor)

tensor([10, 20, 30])
tensor(1400)
<built-in method _make_per_tensor_quantized_tensor of type object at 0x7fa851f81ce0>